### PR TITLE
Add zh_CN for Thaumic Horizons

### PR DESCRIPTION
**Pull request by 3TUSK**
Still not sure if it's right that I renamed en_US.lang to Template.lang.
[Thaumic Horizons] (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-6-thaumcraft-4-addon) is a Thaumcraft addon which adds creature infusion, self-infusion, blood alchemy (essentia potion), lens and even cosmic-related stuff, as well as bunch of new structures.
Credits to @bakaxyf and @Joccob for their help on the zh_CN file. Actually I did most of the zh_CN file, [here comes reference.] (https://github.com/3TUSK/Temp_LocalizationFile/commits/70324d480f1d4b26f6869c205b440913c0239992/Thaumic_Horizons/zh_CN.lang)
Thanks for your time.

### CODE REVIEW

**Comment by fewizz** [comment]
I think, problem in my computer?  Send me your ScreenShot please.
image

**Comment by bakaxyf** [comment]
fk2 goz4o7cndembhzjxqk

**Comment by fewizz** [comment]
Ok, good work! :smile:

**Comment by 3TUSK** [comment]
[s]I bet that I need to check my encoding setting... I am using MacOS X 10.9.5, probably I use Unicode-8[/s]
My typing speed is too slow :(

**Pull request merged**
